#!/usr/bin/env bash

set -eu

mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release \
-DCHIAKI_ENABLE_TESTS=OFF \
-DCHIAKI_ENABLE_CLI=OFF \
-DCHIAKI_ENABLE_GUI=OFF \
-DCHIAKI_ENABLE_ANDROID=OFF \
-DCHIAKI_ENABLE_BOREALIS=OFF \
-DCHIAKI_ENABLE_SETSU=OFF \
-DCHIAKI_ENABLE_STEAMDECK_NATIVE=OFF \
-DCHIAKI_LIB_ENABLE_OPUS=ON \
-DCHIAKI_ENABLE_SPEEX=OFF \
-DCHIAKI_ENABLE_RUDP=ON \
-DCHIAKI_ENABLE_FFMPEG_DECODER=OFF \
-DCHIAKI_ENABLE_PI_DECODER=OFF \
-DCHIAKI_LIB_ENABLE_MBEDTLS=ON \
-DCHIAKI_LIB_MBEDTLS_EXTERNAL_PROJECT=ON \
-DCHIAKI_LIB_OPENSSL_EXTERNAL_PROJECT=OFF \
-DCHIAKI_GUI_ENABLE_SDL_GAMECONTROLLER=OFF \
-DCHIAKI_CLI_ARGP_STANDALONE=OFF \
-DCHIAKI_ENABLE_STEAM_SHORTCUT=OFF \
-DCHIAKI_USE_SYSTEM_JERASURE=OFF \
-DCHIAKI_USE_SYSTEM_NANOPB=OFF \
-DCHIAKI_USE_SYSTEM_CURL=OFF \
-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
-DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
cmake --build .
